# Generated by Django 5.1.2 on 2024-11-07 06:42

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the department', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligation_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Serial number must be in the format 000-00-00-0000', regex='^\\d{3}-\\d{2}-\\d{2}-\\d{4}$')])),
                ('payee', models.CharField(help_text='Payee of the document', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Brief description of the document')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('file_upload', models.FileField(help_text='Upload the document file', upload_to='documents/')),
                ('current_status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(help_text='User who uploaded the document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('forwarded_to', models.ForeignKey(blank=True, help_text='Department to which the document is forwarded', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_documents', to='tracking.department')),
                ('initial_department', models.ForeignKey(blank=True, help_text='Department from which the document was encoded', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encoder_department', to='tracking.department')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.document')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Process', 'In Process'), ('Returned', 'Returned'), ('Forwarded', 'Forwarded'), ('Received', 'Received')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.department')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='tracking.document')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalDocumentStatus',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Process', 'In Process'), ('Returned', 'Returned'), ('Forwarded', 'Forwarded'), ('Received', 'Received')], max_length=50)),
                ('timestamp', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tracking.department')),
                ('document', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tracking.document')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical document status',
                'verbose_name_plural': 'historical document statuss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracking.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
