# Generated by Django 4.2.16 on 2024-11-26 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='dv_number',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Number must be in the format 000-00-00-0000', regex='^\\d{3}-\\d{2}-\\d{2}-\\d{4}$')], verbose_name='Disbursement Voucher Number'),
        ),
    ]
