# Generated by Django 5.1.2 on 2024-11-07 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='obligation_number',
            field=models.CharField(help_text='Enter the obligation number in the format 000-00-00-0000.', max_length=14, validators=[django.core.validators.RegexValidator(message='Serial number must be in the format 000-00-00-0000', regex='^\\d{3}-\\d{2}-\\d{2}-\\d{4}$')]),
        ),
    ]
