# Generated by Django 4.2.16 on 2024-11-28 01:22

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_document_five_prcnt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(error_messages='This field is required.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='expense_class',
            field=models.CharField(choices=[('MOOE', 'MOOE'), ('PS', 'PS'), ('CO', 'CO')], max_length=10, null=True, verbose_name='Expense Class'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_upload',
            field=models.FileField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='five_prcnt',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='document',
            name='one_five_prcnt',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='document',
            name='one_prcnt_frst',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='document',
            name='one_prcnt_scnd',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='document',
            name='payee',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='six_prcnt',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='document',
            name='three_prcnt',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='document',
            name='two_prcnt',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.CreateModel(
            name='ResponsibilityCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc_code', models.CharField(blank=True, default=0, max_length=45)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.document')),
            ],
        ),
    ]
