# Generated by Django 4.2.16 on 2024-11-29 07:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0004_alter_document_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentactivity',
            name='notified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='document',
            name='obligation_number',
            field=models.CharField(error_messages='Incorrect Format!', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Number must be in the format 000-00-00-0000', regex='^\\d{3}-\\d{2}-\\d{2}-\\d{4}$')], verbose_name='Obligation Request Number'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
