# Generated by Django 4.2.16 on 2024-11-29 08:00

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_documentactivity_notified_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='document',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Enter the phone number for notifications', max_length=128, null=True, region=None),
        ),
    ]
