# Generated by Django 4.2.16 on 2024-11-29 14:48

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_remove_profile_phone_number_document_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='obligation_number',
            field=models.CharField(error_messages='Incorrect Format!', max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Number must be in the format 000-00-00-0000', regex='^\\d{3}-\\d{2}-\\d{2}-\\d{4}$')], verbose_name='Obligation Request Number'),
        ),
        migrations.AlterField(
            model_name='document',
            name='obr_date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Obligation Request Date'),
        ),
    ]
