# Generated by Django 4.2.16 on 2024-11-29 15:03

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_alter_document_obligation_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='expense_class',
            field=models.CharField(blank=True, choices=[('MOOE', 'MOOE'), ('PS', 'PS'), ('CO', 'CO')], max_length=10, null=True, verbose_name='Expense Class'),
        ),
        migrations.AlterField(
            model_name='document',
            name='obligation_number',
            field=models.CharField(blank=True, error_messages='Incorrect Format!', max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Number must be in the format 000-00-00-0000', regex='^\\d{3}-\\d{2}-\\d{2}-\\d{4}$')], verbose_name='Obligation Request Number'),
        ),
        migrations.AlterField(
            model_name='document',
            name='obr_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Obligation Request Date'),
        ),
        migrations.AlterField(
            model_name='document',
            name='rc_code',
            field=models.ForeignKey(blank=True, help_text='Responsibility Center', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracking.responsecenter', verbose_name='Responsibility Center'),
        ),
    ]
