# Generated by Django 4.2.16 on 2024-11-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_alter_document_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibilitycenter',
            name='rc_code',
            field=models.CharField(blank=True, default=None, max_length=45),
        ),
    ]
