# Generated by Django 4.2.16 on 2024-11-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_alter_responsibilitycenter_rc_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(error_messages='This field is required.', null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='payee',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
