# Generated by Django 4.2.16 on 2024-11-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_alter_document_description_alter_document_payee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(error_messages='This field is required.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='payee',
            field=models.CharField(max_length=255),
        ),
    ]
